export enum ActionTypes {
  GET_CURRENT_WEATHER = "GET_CURRENT_WEATHER",
  SET_CURRENT_LOCATION_NAME = "GET_CURRENT_LOCATION_NAME",
  GET_WEEKLY_FORECAST = "GET_WEEKLY_FORECAST",
  GET_ALL_FORECAST_DATA = "GET_ALL_FORECAST_DATA",
  ADD_FAVORITE = "ADD_FAVORITE",
  ADD_FAVORITES = "GET_FAVORITES",
  DELETE_FAVORITE = "DELETE_FAVORITE",
  SET_TEMP_UNIT = "SET_TEMP_UNIT"
}